# Generated by Django 4.1 on 2022-09-30 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.CharField(max_length=100)),
                ('discounted', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Uter Pardesh', 'Uter Pardesh'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Gujrat', 'Gujrat'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Himachal Pardesh', 'Himachal Pardesh')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.favbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
