# Generated by Django 4.1 on 2022-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_favbooks_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favbooks',
            name='auther',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='favbooks',
            name='date',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='favbooks',
            name='rating',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='favbooks',
            name='rating_count',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
